[package]
name = "xrf-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.0", features = ["derive", "default"] }
env_logger = "0.11.1"
log = "0.4.20"
xray-db = { path = "../../crates/xray-db" }
