[package]
name = "xray-icon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ddsfile = "0.5.1"
image_dds = "0.5.1"
image = "0.24.9"
xray-ltx = { path = "../xray-ltx" }
