[package]
name = "stalker-xrf-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
clap = { version = "4.5.0", features = ["derive"] }
enum-map = "2.7.3"
env_logger = "0.11.1"
fileslice = "0.4.0"
lazy_static = "1.4.0"
log = "0.4.20"
parquet = "50.0.0"
phf = { version = "0.11.2", features = ["macros"]}
bytes = "1.5.0"
