[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]

[tasks.doc]

[tasks.format]
description = "Format rust codebase."
command = "cargo"
args = ["fmt"]

[tasks.format-check]
description = "Check format of rust codebase."
workspace = false
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.lint]
description = "Lint rust codebase with clippy tool."
workspace = false
command = "cargo"
args = ["clippy"]

[tasks.build-cli]
description = "Build CLI application in debug mode."
workspace = false
dependencies = [
  { name = "build", path = "bin/xrf-cli" },
]

[tasks.build-cli-release]
description = "Build CLI application in release mode."
workspace = false
dependencies = [
  { name = "build-release", path = "bin/xrf-cli" },
]

[tasks.build-app]
description = "Build UI application in debug mode."
workspace = false
dependencies = [
  { name = "build", path = "bin/xrf-app" },
]

[tasks.build-app-release]
description = "Build UI application in release mode."
workspace = false
dependencies = [
  { name = "build-release", path = "bin/xrf-app" },
]

[tasks.dev-app]
description = "Run UI application backend and frontend in watch mode."
workspace = false
dependencies = [
  { name = "dev", path = "bin/xrf-app" },
]

[tasks.serve-backend]
description = "Run UI application backend in watch mode."
workspace = false
dependencies = [
  { name = "serve-backend", path = "bin/xrf-app" },
]

[tasks.serve-ui]
description = "Run UI application frontend in watch mode."
workspace = false
dependencies = [
  { name = "serve-ui", path = "bin/xrf-app" },
]
