[package]
name = "xray-archive"
version = "0.1.0"
edition = "2021"
resolver = "2"

[lib]
path = "src/lib.rs"

[dependencies]
byteorder = "1.4.3"
bytes = "1.5.0"
crc32fast = "1.3.2"
delharc = { path = "../xray-delharc", features = ["lh1"] }
encoding_rs = "0.8.33"
env_logger = "0.11.1"
fileslice = "0.4.0"
log = "0.4.20"
minilzo-rs = "0.6.1"
regex = "1.10.3"
walkdir = "2.5.0"

[dev-dependencies]
xray-test-utils = { path = "../xray-test-utils" }
