[package]
name = "xray-gamedata"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
log = "0.4.22"
thiserror = "2.0.10"
walkdir = "2.5.0"
xray-db = { path = "../xray-db" }
xray-ltx = { path = "../xray-ltx" }
