[package]
name = "xray-gamedata"
version = "0.1.0"
edition = "2021"

[dependencies]
xray-db = { path = "../xray-db" }
xray-ltx = { path = "../xray-ltx" }
log = "0.4.22"
walkdir = "2.5.0"
thiserror = "2.0.10"
