[package]
name = "xray-gamedata"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
ddsfile = "0.5.2"
image = "0.25.5"
image_dds = "0.7.0"
log = "0.4.22"
regex = "1.11.1"
thiserror = "2.0.10"
walkdir = "2.5.0"
xray-db = { path = "../xray-db" }
xray-ltx = { path = "../xray-ltx" }
rayon = "1.10.0"
