[package]
name = "delharc"
version = "0.5.0"
authors = ["Rafal Michalski <royaltm75@gmail.com>"]
edition = "2021"
description = "A library for parsing and extracting files from LHA/LZH archives."
categories = ["compression"]
keywords = ["LHA", "LZH", "UNLHA"]
homepage = "https://github.com/royaltm/rust-delharc"
repository = "https://github.com/royaltm/rust-delharc"
license = "MIT OR Apache-2.0"
readme = "README.md"
exclude = [".github", ".gitignore", "tests/*", "examples/*"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["lh1", "lz"]
lh1 = []
lhx = []
lz = []

[dependencies]
chrono = "0.4"
bitflags = "2.3"
memchr = { version = "2", default-features = false }

[dev-dependencies]
crc-any = "2.4"
rand = "0.8.5"
