[package]
name = "xray-icon"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
ddsfile = "0.5.1"
image = "0.24.9"
image_dds = "0.5.1"
path-absolutize = "3.1.1"
roxmltree = "0.19.0"
serde = { version = "1.0.197", features = ["derive"] }
xray-ltx = { path = "../xray-ltx" }