[package]
name = "xray-texture"
version = "0.1.0"
edition = "2021"

[dependencies]
ddsfile = "0.5.2"
image = "0.25.5"
image_dds = "0.7.0"
path-absolutize = "3.1.1"
roxmltree = "0.19.0"
serde = { version = "1.0.197", features = ["derive"] }
xray-ltx = { path = "../xray-ltx" }
rayon = "1.10.0"
log = "0.4.22"
thiserror = "2.0.11"
