[package]
name = "xray-error"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "2.0.11"
xray-error-derive = { path = "../xray-error-derive" }

[lints]
workspace = true