[package]
name = "xray-ltx"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
path = "src/lib.rs"

[dependencies]
cfg-if = "1.0"
unicase = "2.7.0"
ordered-multimap = "0.7"

[features]
default = []
