[package]
name = "xrf-app"
version = "0.1.0"
description = "XRF development tools"
authors = ["Neloreck"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "path-all", "fs-exists", "dialog-save", "dialog-ask", "dialog-open", "dialog-confirm", "shell-open"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
xray-db = { path = "../../crates/xray-db" }
env_logger = "0.11.2"
log = "0.4.21"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
