[package]
name = "xrf-app"
version = "0.1.0"
description = "XRF development tools"
authors = ["Neloreck"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-rc.8", features = [
  "codegen"
] }

[dependencies]
env_logger = "0.11.2"
image = "0.24.9"
log = "0.4.21"
percent-encoding = "2.3.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tauri = { version = "2.0.0-rc.9", features = [] }
tauri-plugin-dialog = "2.0.0-rc"
tauri-plugin-fs = "2.0.0-rc"
tauri-plugin-shell = "2.0.0-rc"
xray-archive = { path = "../../crates/xray-archive" }
xray-db = { path = "../../crates/xray-db" }
xray-export = { path = "../../crates/xray-export" }
xray-icon = { path = "../../crates/xray-texture" }
xray-ltx = { path = "../../crates/xray-ltx" }

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
