[package]
name = "xrf-app"
version = "0.1.0"
description = "XRF development tools"
authors = ["Neloreck"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.5", features = [
    "codegen"
] }

[dependencies]
env_logger = "0.11.6"
log = "0.4.25"
percent-encoding = "2.3.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tauri = { version = "2.2.5", features = [] }
tauri-plugin-dialog = "2.2.0"
tauri-plugin-fs = "2.2.0"
tauri-plugin-shell = "2.2.0"
xray-archive = { path = "../../crates/xray-archive" }
xray-db = { path = "../../crates/xray-db" }
xray-export = { path = "../../crates/xray-export" }
xray-ltx = { path = "../../crates/xray-ltx" }
xray-texture = { path = "../../crates/xray-texture" }
xray-translation = { path = "../../crates/xray-translation" }

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[lints]
workspace = true
