name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: davidB/rust-cargo-make@v1
    - uses: actions/checkout@v3
    - name: Build CLI
      run: cargo make build-cli-release
    - name: Run tests
      run: cargo make test
    - name: Run formatter
      run: cargo fmt --all -- --check
