name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: davidB/rust-cargo-make@v1
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2

    - name: Build CLI
      run: cargo make build-cli

    - name: Run xray-db tests
      run: cargo test --verbose -p xray-db

    - name: Run formatter
      run: cargo fmt --all -- --check
